executor: cluster-generic
jobs: 5

default-resources:
    runtime: 30
    mem_mb: 16000
    cpus_per_task: 1
    partition: "short.q"
    slurm_account: "project_2010176"
    gres: "'nvme:0'"
    metaspades_slots: 0

cluster-generic-submit-cmd: "/work_projet/holoruminant/project_Pipeline-Holoruminant-Meta/submit.sh {resources.runtime} {resources.mem_mb} {resources.cpus_per_task} -q {resources.partition} -A {resources.slurm_account} -N job_{jobid}-{rule} -o jobs_log/job_{jobid}-{rule}.out -e jobs_log/job_{jobid}-{rule}.err"
