executor: cluster-generic
# executor: local
jobs: 5
default-resources:
    time: 7200
    # time: 700
    mem_per_cpu: 10000
    # mem_per_cpu: 4000
    cpu_per_task: 1
    partition: "'long.q'"
    # partition: "'short.q'"
    project: "'project_2009831'"
    nvme: 0
cluster-generic-submit-cmd: "qsub -cwd -l h_rt={resources.time} -l mem_free={resources.mem_per_cpu} -pe thread {resources.cpu_per_task} -q {resources.partition} -A {resources.project} -N job_{jobid}-{rule} -o jobs_log/job_{jobid}-{rule}.out -e jobs_log/job_{jobid}-{rule}.err"